### ISSUE TITLE
Missing columns?

### ISSUE THREAD

**Issue by alvations** [paracrawl/human-evaluations#1]
There's some missing columns in these:

 - sk 	line 102
 - de 	line 147
 - ga 	line 587
 - mt 	line 648
 - mt 	line 723
 - hr  	line 1257

```python
from lazyme import find_files
import swifter
import pandas as pd

column_names = "url1 url2 src trg hunalign zipporah bicleaner evaluation comments".split()

dfs = []
for filename in sorted(set(find_files('.', 'sorted.*'))):
    trg_lang = filename[-2:]
    df = pd.read_csv(filename, sep='\t', names=column_names)
    df['trg_lang'] = trg_lang
    df['line_num'] = np.arange(len(df))
    dfs.append(df)
    
df_all = pd.concat(dfs)

for label, rows in df_all.groupby('evaluation'):
    if label not in ['A', 'E', 'F', 'L', 'MT', 'T', 'V']:
        print('\t'.join(map(str, rows[['trg_lang', 'line_num']].values[0])))
```

**Comment by alvations** [comment]
Oh, there's tabs in either the src or trg =(

**Comment by alvations** [comment]
Ah, found the culprit. There isn't a quote character specified. Are the data columns were concatenated with `paste`?

```python
df = pd.read_csv(filename, sep='\t', names=column_names, quotechar="\0")
```

**Comment by mbanon** [comment]
Hi @alvations , it's not clear to me if there is an actual issue with the data or not ¿?

**Comment by alvations** [comment]
Depends on how one defines a well created tsv. If we just split on tab and specify quote char, it looks okay. If we want to use a default tsv reader that's standard and uses `"` as quotechar then the data will not be read properly
