### ISSUE TITLE
Should we consider these pairs directioned?

### ISSUE THREAD

**Issue by bittlingmayer** [paracrawl/human-evaluations#2]
My understanding is that ParaCrawl sentences can be in either direction, we don't really know what was the original and what was the transltion.

Were the annotations done in a particular direction?

**Comment by gramirez-prompsit** [comment]
Hi, you are right, we don't know. 

Annotations where done by professional translators mastering English (or Spanish from version 7 on) and native in the other language. 

They were presented with pairs of sentences, not labeled as source or target, just as the language they where supposed to be written. The pair of sentences was the unit to label and in some cases the annotations were further specified, e.g. if the annotation was Machine Translation, annotators should indicate which language was machine translated: one, the other or both, also applying to Wrong Language Identification or Translation Error.
